# Generated by Django 5.1.1 on 2025-11-28 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_agence_user_direction_user_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique du service', max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text='Nom du service', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description du service', verbose_name='Description')),
                ('budget_annuel', models.DecimalField(decimal_places=2, default=0, help_text='Budget annuel alloué en FCFA', max_digits=12, verbose_name='Budget annuel')),
                ('actif', models.BooleanField(default=True, help_text='Le service est-il actif ?', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Chef de service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['nom'],
            },
        ),
    ]
