# Generated by Django 5.1.1 on 2025-11-10 17:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VALIDATE', 'Validation'), ('REJECT', 'Rejet'), ('APPROVE', 'Approbation')], help_text="Type d'action effectuée", max_length=20, verbose_name='Action')),
                ('model', models.CharField(help_text='Nom du modèle concerné', max_length=100, verbose_name='Modèle')),
                ('object_id', models.UUIDField(help_text="UUID de l'objet concerné", verbose_name="ID de l'objet")),
                ('old_value', models.TextField(blank=True, help_text='Valeur avant modification (JSON)', null=True, verbose_name='Valeur ancienne')),
                ('new_value', models.TextField(blank=True, help_text='Valeur après modification (JSON)', null=True, verbose_name='Nouvelle valeur')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True, verbose_name='Adresse IP')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, help_text="Montant de l'avance en FCFA", max_digits=12, verbose_name='Montant')),
                ('date_versement', models.DateTimeField(blank=True, help_text="Date à laquelle l'avance a été versée", null=True, verbose_name='Date de versement')),
                ('statut', models.CharField(choices=[('DEMANDEE', 'Demandée'), ('APPROUVEE', 'Approuvée'), ('VERSEEE', 'Versée'), ('ANNULEE', 'Annulée'), ('REMBOURSEE', 'Remboursée')], default='DEMANDEE', help_text="Statut de l'avance", max_length=20, verbose_name='Statut')),
                ('mode_versement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], default='ESPECES', help_text="Mode de versement de l'avance", max_length=20, verbose_name='Mode de versement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='Destination de la mission', max_length=100, verbose_name='Destination')),
                ('fonction', models.CharField(help_text='Fonction du personnel', max_length=100, verbose_name='Fonction')),
                ('montant_par_jour', models.DecimalField(decimal_places=2, help_text='Montant journalier en FCFA', max_digits=10, verbose_name='Montant par jour')),
                ('date_debut', models.DateField(help_text='Date de début de validité', verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de validité', null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, help_text='Le barème est-il actif ?', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Barème',
                'verbose_name_plural': 'Barèmes',
                'ordering': ['-date_debut', 'destination'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('TRANSPORT', 'Transport'), ('HEBERGEMENT', 'Hébergement'), ('RESTAURATION', 'Restauration'), ('CARBURANT', 'Carburant'), ('PEAGE', 'Péage'), ('DIVERS', 'Dépenses diverses')], help_text='Nature de la dépense', max_length=20, verbose_name='Nature')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant de la dépense en FCFA', max_digits=12, verbose_name='Montant')),
                ('date_depense', models.DateField(help_text='Date à laquelle la dépense a été effectuée', verbose_name='Date de dépense')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la dépense', verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='EtatDepenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(help_text="Fichier PDF de l'état des dépenses", upload_to='etats_depenses/', verbose_name='Fichier')),
                ('total_depenses', models.DecimalField(decimal_places=2, help_text='Total des dépenses en FCFA', max_digits=12, verbose_name='Total des dépenses')),
                ('solde', models.DecimalField(decimal_places=2, help_text='Solde restant en FCFA', max_digits=12, verbose_name='Solde')),
                ('valide', models.BooleanField(default=False, help_text="L'état des dépenses est-il validé ?", verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'État des dépenses',
                'verbose_name_plural': 'États des dépenses',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(default='JUSTIFICATIF', help_text='Type de document justificatif', max_length=50, verbose_name='Type de document')),
                ('categorie', models.CharField(blank=True, help_text='Catégorie détaillée du justificatif', max_length=100, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du justificatif', verbose_name='Description')),
                ('fichier', models.FileField(blank=True, help_text='Justificatif scanné ou photo', null=True, upload_to='justificatifs/%Y/%m/', verbose_name='Fichier')),
                ('nom_fichier', models.CharField(blank=True, help_text='Nom original du fichier téléchargé', max_length=255, verbose_name='Nom du fichier')),
                ('taille', models.BigIntegerField(default=0, help_text='Taille du fichier en octets', verbose_name='Taille')),
                ('hash_md5', models.CharField(blank=True, help_text="Hash MD5 du fichier pour vérification d'intégrité", max_length=32, verbose_name='Hash MD5')),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'upload")),
                ('verifie', models.BooleanField(default=False, help_text='Le justificatif a-t-il été vérifié ?', verbose_name='Vérifié')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('commentaire_verification', models.TextField(blank=True, verbose_name='Commentaire de vérification')),
                ('montant', models.DecimalField(decimal_places=2, default=0, help_text='Montant en FCFA', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('devise', models.CharField(default='XAF', help_text='Code devise ISO (XAF pour FCFA)', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=10, verbose_name='Statut')),
                ('commentaire_validation', models.TextField(blank=True, verbose_name='Commentaire de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_remboursement', models.DateTimeField(blank=True, null=True, verbose_name='Date de remboursement')),
            ],
            options={
                'verbose_name': 'Justificatif',
                'verbose_name_plural': 'Justificatifs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='TEMP-REF', help_text='Référence unique de la mission', max_length=50, unique=True, verbose_name='Référence')),
                ('titre', models.CharField(help_text='Titre descriptif de la mission', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la mission', verbose_name='Description')),
                ('type', models.CharField(choices=[('FORMATION', 'Formation'), ('REUNION', 'Réunion'), ('MISSION_COMMERCIALE', 'Mission commerciale'), ('AUDIT', 'Audit'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de mission')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('EN_COURS', 'En cours'), ('RETOUR', 'Retour déclaré'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=15, verbose_name='Statut')),
                ('date_debut', models.DateField(help_text='Date de début de la mission', verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text='Date de fin de la mission', verbose_name='Date de fin')),
                ('lieu_mission', models.CharField(help_text='Lieu où se déroule la mission', max_length=200, verbose_name='Lieu de mission')),
                ('budget_estime', models.DecimalField(decimal_places=2, default=0, help_text='Budget estimé pour la mission en FCFA', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget estimé')),
                ('avance_demandee', models.DecimalField(decimal_places=2, default=0, help_text="Montant d'avance demandé en FCFA", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avance demandée')),
                ('avance_versee', models.BooleanField(default=False, help_text="L'avance a-t-elle été versée ?", verbose_name='Avance versée')),
                ('signatures_completes', models.BooleanField(default=False, help_text='Toutes les signatures financières sont-elles complètes ?', verbose_name='Signatures complètes')),
                ('date_debut_reelle', models.DateTimeField(blank=True, help_text='Date réelle de début de la mission', null=True, verbose_name='Date de début réelle')),
                ('date_retour_reelle', models.DateTimeField(blank=True, help_text="Date réelle de retour de mission déclarée par l'agent", null=True, verbose_name='Date de retour réelle')),
                ('retour_declare', models.BooleanField(default=False, help_text="L'agent a-t-il déclaré son retour ?", verbose_name='Retour déclaré')),
                ('date_limite_justificatifs', models.DateTimeField(blank=True, help_text='Date limite pour déposer les justificatifs (72h après retour)', null=True, verbose_name='Date limite justificatifs')),
                ('justificatifs_deposes', models.BooleanField(default=False, help_text='Tous les justificatifs ont-ils été déposés ?', verbose_name='Justificatifs déposés')),
                ('justificatifs_verifies', models.BooleanField(default=False, help_text='Les justificatifs ont-ils été vérifiés par RH ?', verbose_name='Justificatifs vérifiés')),
                ('relance_justificatifs', models.BooleanField(default=False, help_text='Une relance pour les justificatifs a-t-elle été effectuée ?', verbose_name='Relance justificatifs')),
                ('date_derniere_relance_justificatifs', models.DateTimeField(blank=True, null=True, verbose_name='Date dernière relance justificatifs')),
                ('solde_calcule', models.DecimalField(decimal_places=2, default=0, help_text='Solde final calculé (positif = FUCEC doit rembourser, négatif = agent doit rembourser)', max_digits=12, verbose_name='Solde calculé')),
                ('cloturee', models.BooleanField(default=False, help_text='La mission est-elle clôturée ?', verbose_name='Clôturée')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('archivee', models.BooleanField(default=False, help_text='La mission est-elle archivée ?', verbose_name='Archivée')),
                ('date_archivage', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MissionIntervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_dans_mission', models.CharField(blank=True, help_text="Rôle spécifique de l'intervenant dans cette mission", max_length=100, verbose_name='Rôle dans la mission')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Intervenant de mission',
                'verbose_name_plural': 'Intervenants de mission',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la notification', max_length=200, verbose_name='Titre')),
                ('message', models.TextField(help_text='Contenu de la notification', verbose_name='Message')),
                ('type', models.CharField(choices=[('VALIDATION', 'Validation'), ('RAPPEL', 'Rappel'), ('APPROBATION', 'Approbation'), ('REJET', 'Rejet'), ('INFO', 'Information')], default='INFO', help_text='Type de notification', max_length=20, verbose_name='Type')),
                ('lue', models.BooleanField(default=False, help_text='La notification a-t-elle été lue ?', verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('lien', models.URLField(blank=True, help_text='Lien vers la ressource concernée', verbose_name='Lien')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SignatureFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('AGENT', 'Agent'), ('CHEF_AGENCE', "Chef d'agence"), ('DIRECTEUR_FINANCES', 'Directeur Finances'), ('COMPTABLE', 'Comptable'), ('DG', 'Directeur Général')], help_text='Niveau de signature requis', max_length=20, verbose_name='Niveau')),
                ('date_signature', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('ordre', models.PositiveIntegerField(default=1, help_text='Ordre dans le processus de signature', verbose_name='Ordre')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SIGNE', 'Signé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', help_text='Statut de la signature', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire du signataire', verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_limite_signature', models.DateTimeField(blank=True, help_text='Date et heure limite pour la signature (72h)', null=True, verbose_name='Date limite de signature')),
                ('relance_effectuee', models.BooleanField(default=False, help_text='Une relance automatique a-t-elle été envoyée ?', verbose_name='Relance effectuée')),
                ('date_derniere_relance', models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière relance')),
            ],
            options={
                'verbose_name': 'Signature financière',
                'verbose_name_plural': 'Signatures financières',
                'ordering': ['mission', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numéro unique du ticket', max_length=50, unique=True, verbose_name='Numéro')),
                ('montant_approuve', models.DecimalField(decimal_places=2, help_text='Montant approuvé en FCFA', max_digits=12, verbose_name='Montant approuvé')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('statut', models.CharField(choices=[('EMIS', 'Émis'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé'), ('PAYE', 'Payé')], default='EMIS', help_text='Statut du ticket', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('N_PLUS_1', 'N+1 (Chef direct)'), ('N_PLUS_2', 'N+2 (Chef du N+1)'), ('DGA_DG', 'DGA/DG (Direction)')], max_length=20, verbose_name='Niveau de validation')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('REPORTEE', 'Reportée')], default='EN_ATTENTE', max_length=10, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire du valideur', verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('ordre', models.PositiveIntegerField(default=1, help_text='Ordre dans le processus de validation', verbose_name='Ordre de validation')),
                ('delai_heures', models.PositiveIntegerField(default=24, help_text='Délai imparti pour la validation en heures', verbose_name='Délai en heures')),
                ('date_echeance', models.DateTimeField(blank=True, help_text='Date et heure limite pour la validation', null=True, verbose_name="Date d'échéance")),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si cette validation est toujours active', verbose_name='Validation active')),
            ],
            options={
                'verbose_name': 'Validation',
                'verbose_name_plural': 'Validations',
                'ordering': ['mission', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(help_text="Numéro d'immatriculation", max_length=20, unique=True, verbose_name='Immatriculation')),
                ('marque', models.CharField(help_text='Marque du véhicule', max_length=50, verbose_name='Marque')),
                ('modele', models.CharField(help_text='Modèle du véhicule', max_length=50, verbose_name='Modèle')),
                ('type', models.CharField(choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('CAMION', 'Camion'), ('BUS', 'Bus')], default='VOITURE', help_text='Type de véhicule', max_length=20, verbose_name='Type')),
                ('disponible', models.BooleanField(default=True, help_text='Le véhicule est-il disponible ?', verbose_name='Disponible')),
                ('kilometrage', models.PositiveIntegerField(default=0, help_text='Kilométrage actuel', verbose_name='Kilométrage')),
                ('date_acquisition', models.DateField(help_text="Date d'acquisition du véhicule", verbose_name="Date d'acquisition")),
                ('date_assurance', models.DateField(help_text="Date d'expiration de l'assurance", verbose_name="Date d'assurance")),
                ('date_visite', models.DateField(help_text='Date de la prochaine visite technique', verbose_name='Date de visite')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['immatriculation'],
            },
        ),
    ]
