# Generated by Django 5.1.1 on 2025-11-10 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='avance',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_recues', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire'),
        ),
        migrations.AddField(
            model_name='avance',
            name='verse_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_versees', to=settings.AUTH_USER_MODEL, verbose_name='Versée par'),
        ),
        migrations.AlterUniqueTogether(
            name='bareme',
            unique_together={('destination', 'fonction', 'date_debut')},
        ),
        migrations.AddField(
            model_name='etatdepenses',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etats_depenses_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='justificatif',
            name='intervenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to=settings.AUTH_USER_MODEL, verbose_name='Intervenant'),
        ),
        migrations.AddField(
            model_name='justificatif',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AddField(
            model_name='justificatif',
            name='valideur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validateur'),
        ),
        migrations.AddField(
            model_name='justificatif',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_verifies', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='mission',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_conduites', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur'),
        ),
        migrations.AddField(
            model_name='mission',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='mission',
            name='entite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='users.entite', verbose_name='Entité'),
        ),
        migrations.AddField(
            model_name='mission',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='missions_participees', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='justificatif',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='etatdepenses',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_depenses', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='depense',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='avance',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='missionintervenant',
            name='intervenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Intervenant'),
        ),
        migrations.AddField(
            model_name='missionintervenant',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AddField(
            model_name='signaturefinanciere',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures_financieres', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='signaturefinanciere',
            name='signataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures_financieres', to=settings.AUTH_USER_MODEL, verbose_name='Signataire'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_emis', to=settings.AUTH_USER_MODEL, verbose_name='Émetteur'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='validation',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='missions.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='validation',
            name='valideur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Validateur'),
        ),
        migrations.AddField(
            model_name='mission',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='missions.vehicule', verbose_name='Véhicule'),
        ),
        migrations.AlterUniqueTogether(
            name='missionintervenant',
            unique_together={('mission', 'intervenant')},
        ),
        migrations.AlterUniqueTogether(
            name='signaturefinanciere',
            unique_together={('mission', 'niveau')},
        ),
        migrations.AlterUniqueTogether(
            name='validation',
            unique_together={('mission', 'valideur', 'niveau')},
        ),
    ]
