# Generated by Django 5.1.1 on 2025-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='reference',
            field=models.CharField(help_text='Référence unique de la mission', max_length=50, unique=True, verbose_name='Référence'),
        ),
    ]
