# Generated by Django 5.1.1 on 2025-11-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_update_mission_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique du type de frais', max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(help_text='Libellé du type de frais', max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du type de frais', verbose_name='Description')),
                ('plafond', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond journalier en FCFA (si applicable)', max_digits=12, null=True, verbose_name='Plafond')),
                ('remboursable', models.BooleanField(default=True, help_text='Indique si ce type de frais est remboursable', verbose_name='Remboursable')),
                ('actif', models.BooleanField(default=True, help_text='Indique si ce type de frais est actif', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de frais',
                'verbose_name_plural': 'Types de frais',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique du type de mission', max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(help_text='Libellé du type de mission', max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du type de mission', verbose_name='Description')),
                ('actif', models.BooleanField(default=True, help_text='Indique si ce type de mission est actif', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de mission',
                'verbose_name_plural': 'Types de mission',
                'ordering': ['libelle'],
            },
        ),
    ]
