# Generated by Django 5.1.1 on 2025-11-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_typefrais_typemission'),
    ]

    operations = [
    ]
