# Generated by Django 5.1.1 on 2025-11-27 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, verbose_name='Année')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant alloué')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-annee'],
            },
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis au chef de service'), ('VISE_DSI', 'Visé par le chef de service'), ('VISE_DG', 'Visé par le Directeur Général'), ('VALIDEE', 'Validée'), ('EN_COURS', 'En cours'), ('RETOUR', 'Retour déclaré'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], default='BROUILLON', max_length=15, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('delegant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Délégant')),
                ('delegataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Délégaire')),
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission', verbose_name='Mission')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Entrée historique',
                'verbose_name_plural': 'Historique des missions',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='OrdreMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_signature', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('statut', models.CharField(default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordre_mission', to='missions.mission', verbose_name='Mission')),
                ('signataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_signes', to=settings.AUTH_USER_MODEL, verbose_name='Signataire')),
            ],
            options={
                'verbose_name': 'Ordre de mission',
                'verbose_name_plural': 'Ordres de mission',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RapportFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport_final', to='missions.mission', verbose_name='Mission')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Rapport final',
                'verbose_name_plural': 'Rapports finaux',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='OrdreMissionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.PositiveIntegerField(verbose_name='Étape')),
                ('statut', models.CharField(default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('ordre_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences_validation', to='missions.ordremission', verbose_name='Ordre de mission')),
                ('signataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Signataire')),
            ],
            options={
                'verbose_name': 'Séquence de validation',
                'verbose_name_plural': 'Séquences de validation',
                'ordering': ['ordre_mission', 'etape'],
                'unique_together': {('ordre_mission', 'etape')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.PositiveIntegerField(verbose_name='Niveau')),
                ('role_validation', models.CharField(max_length=100, verbose_name='Rôle de validation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('type_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows_validation', to='missions.typemission', verbose_name='Type de mission')),
            ],
            options={
                'verbose_name': 'Étape de validation',
                'verbose_name_plural': 'Workflow de validation',
                'ordering': ['type_mission', 'niveau'],
                'unique_together': {('type_mission', 'niveau')},
            },
        ),
    ]
