# Generated by Django 5.1.1 on 2025-11-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_budget_alter_mission_statut_delegation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='moyen_transport',
            field=models.CharField(blank=True, help_text='Moyen de transport utilisé (VOITURE, AVION, etc.)', max_length=50, null=True, verbose_name='Moyen de transport'),
        ),
    ]
