# Generated by Django 5.1.1 on 2025-11-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_mission_moyen_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='moyen_transport',
            field=models.CharField(default='VOITURE', help_text='Moyen de transport utilisé (VOITURE, AVION, etc.)', max_length=50, verbose_name='Moyen de transport'),
        ),
    ]
