# Generated by Django 5.1.1 on 2025-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_alter_mission_moyen_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='objet_mission',
            field=models.TextField(default='', help_text='Objet et objectifs de la mission', verbose_name='Objet de la mission'),
        ),
    ]
