# Generated by Django 5.1.1 on 2025-11-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_mission_objet_mission'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS budget_alloue;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS destination;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS montant_total;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS niveau_validation_actuel;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS pays_destination;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS priorite;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS service_id;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS ordre_genere;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS date_generation_ordre;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS fichier_ordre_mission;
            ALTER TABLE missions_mission DROP COLUMN IF EXISTS numero_ordre;
            """,
            reverse_sql="""
            -- Pas de reverse pour cette migration
            """
        ),
    ]
